---
- hosts: localhost

  vars:
          ansible_connection: local
          # satellite_server: FQDN
          #
          # Option 1
          reg_activation_key: myregistration
          reg_organization_id: 123456

          #
          # Option 2:
          #    reg_pool:
          #    reg_pool_ids:
          #    reg_username:
          #    reg_password:
          #
          # The following are optional
          reg_server_insecure: yes
          reg_autosubscribe: yes
          reg_osrelease: 7.4

          # Set this variable to true if you want to remove/disable all previously existing repositories. The default is false
          repo_reset: true

          repositories:
                  - rhel-7-server-rpms
                  - rhel-sap-hana-for-rhel-7-server-rpms

  roles:
    - subscribe-rhn
